### ISSUE TITLE
[Bug]: precedence/ordering of @@access decorators is unclear

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/typespec-azure#1036] opened 2024-06-18 17:08 UTC
### Describe the bug

I've got a question about `@@access`, when there are rules that overlap.

In our service we were attempting to make an operation public, only for the scope "go", but internal for everyone else. However, we couldn't do this:

```typespec
@@access(TestThing, Access.internal);
@@access(TestThing, Access.public, "go");
```

This generates this type graph:

```yaml
ModelTestThing
  properties:
    ModelPropertyname
      # extra stuff elided
      data:
         # NOTE that it just gave us all the same access.
         Symbol(@azure-tools/typespec-client-generator-core.access): { }
```

You can fix this by just ordering them differently:

```typespec
@@access(TestThing, Access.public, "go");
@@access(TestThing, Access.internal);
```

This generates this type graph:

```yaml
ModelTestThing
  properties:
    ModelPropertyname
      # extra stuff elided
      data:
         Symbol(@azure-tools/typespec-client-generator-core.access): { go: "public" }
```

I'm not entirely sure which behavior is the correct behavior, but I did find it surprising that the more specific directive was overridden by the least specific directive. The ordering of their declarations in the file doesn't seem like it should be a critical factor, especially given how these `@@access`'s could be in separate files altogether.

Including @l0lawrence and @lmazuel in case I've misstated the bug.

### Reproduction

[Playground Link](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3ytjLWNsaWVudC1nZW5lcmF0b3LINgp1c2luZyBUeXBlU3BlYy5IdHRwO9AVUmVzdNEVVukAqMgbQcR5LkNvcmXSEi5UcmFpdHPPGeUAlUfoAJTHOwptb2RlbCBUZXN0VGjELXsKICAvKioKICAgKiBIZWxsbyB3b3JsZMURLwogIG5hbWU6IHN0cuUAjX0KCi8vIHJl5QFJbmcgdGhlIG9yZGVyIG9mxA1zZSBzdGF0ZW1lbnRzIHdpbGzET2sKQEBhY2Nlc3MoyXosIEHFEi5wdWJsaWMsICJnbyIpO9wqaW50ZXJuYWwpOwoKCg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fdata-plane%22%5D%7D%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by richardpark-msft** [comment] 2024-06-18 17:10
@iscai-msft, @lmazuel asked that this be assigned to you specifically.

**Comment by iscai-msft** [comment] 2024-06-18 20:48
this seems like a bug, let me take a look at it today

**Comment by richardpark-msft** [comment] 2024-06-18 20:57
@iscai-msft, just a note, there's another issue that @lmazuel filed about handling CSV lists inside of the 'scope' string as well. The use case was similar to what we were trying to accomplish here.

Issue: https://github.com/Azure/typespec-azure/issues/978

**Comment by iscai-msft** [comment] 2024-06-18 21:17
@richardpark-msft after looking into it more, we don't want people to set multiple access decorators, because it gets complicated if they conflict with each other. Instead, I think the way around this is adding the ability to do a list of languages, and also adding support for `~` to exclude a language from the list. I'm going to get started on that, and close this issue in favor of #978 if you're ok with that

**Comment by richardpark-msft** [comment] 2024-06-18 22:13
> @richardpark-msft after looking into it more, we don't want people to set multiple access decorators, because it gets complicated if they conflict with each other. Instead, I think the way around this is adding the ability to do a list of languages, and also adding support for `~` to exclude a language from the list. I'm going to get started on that, and close this issue in favor of #978 if you're ok with that

I think so. If the order is ambiguous then it seems like multiple decorators should cause an outright error otherwise your result might be non-deterministic. What do you think of that?

**Comment by iscai-msft** [comment] 2024-06-21 15:11
Yeah that's definitely why we decided originally to not allow multiple instances of either augmentation or direct decorating with `@access` and `@usage`. With the pr adding list of scopes, you should be able to do `@@access("internal", "python,csharp,go,java,javascript")`, which is definitely kind of long. I'm going to start another PR as well in the meantime adding support for `~`, but that will require more review just because we have to determine whether we want to add support for tilde

**Comment by richardpark-msft** [comment] 2024-06-21 18:25
Just to make sure we're talking about the same thing - in the example I gave I am applying it twice though, and there wasn't (AFAICT) an error. Should there have been? Right now it kind of appears to work, but if the resolution of that is ambiguous, depending on order, it seems like it should fail or provide some sort of warning you're putting yourself in that situation.

(the comma separated list is awesome, but I think the error condition is a separate issue)

**Comment by iscai-msft** [comment] 2024-08-07 20:13
Oops I missed this comment. Yeah you're right, there should be a warning raised here. Let me make this a bug and make sure we raise

**Comment by tadelesh** [comment] 2024-08-09 08:44
from our [test](https://github.com/Azure/typespec-azure/blob/845fe16edb871df1e357ac495ba67ad023f11b52/packages/typespec-client-generator-core/test/decorators.test.ts#L1584), this will report an diagnostics. i wonder if it is because the lint rule is not enabled when compiling.

**Comment by tadelesh** [comment] 2024-08-27 03:27
@timotheeguerin in tcgc, i used a core api to report diagnostics (code [here](https://github.com/Azure/typespec-azure/blob/52a93d628b1f04f73ae70224b0ef702df9645beb/packages/typespec-client-generator-core/src/decorators.ts#L126)). it could work when test, but with the real typespec compile, there is no diagnostic reported. could you help to identify if the usage is wrong?

**Comment by tadelesh** [comment] 2024-09-25 06:56
the root cause is previous check does not work on augment decorator.

**Closed** 2024-10-15 06:03 UTC
Labels: bug, lib:tcgc
