### ISSUE TITLE
typespec-azure-core - ResourceList should allow scalars/non-models in the value array

### ISSUE THREAD

**Issue by swathipil** [Azure/typespec-azure#229] opened 2024-02-06 22:45 UTC
Currently, ResourceList expects that the value array only contains models. However, the value array should accept scalars like ints/strings as per a discussion with @catalinaperalta and @johanste.

For example, [this ResourceList operation](https://github.com/Azure/azure-rest-api-specs/blob/fcfef88f6aabe7f55ea234c8ad8a8b6b5ac49cda/specification/schemaregistry/SchemaRegistry/main.tsp#L87) using the resource type Version defined [here](https://github.com/Azure/azure-rest-api-specs/blob/fcfef88f6aabe7f55ea234c8ad8a8b6b5ac49cda/specification/schemaregistry/SchemaRegistry/main.tsp#L220) should allow this: 
```
"body": {
        "value": [
          0,
          1,
          2
        ],
        "nextLink": [link](url)
      }
```
However, it only allows this:
```
"body": {
        "value": [
          {"schemaVersion": 0},
          {"schemaVersion": 1},
          {"schemaVersion": 2}
        ],
        "nextLink": [link](url)
      }
```

As a workaround, I'm defining a non-standard list operation by following this example: https://github.com/Azure/azure-rest-api-specs-pr/pull/15492/files

**Comment by timotheeguerin** [comment] 2024-02-06 23:19
Dup https://github.com/Azure/typespec-azure-pr/issues/3735

**Comment by markcowl** [comment] 2024-09-10 01:44
Closing as duplicate of: https://github.com/Azure/typespec-azure/issues/262

**Closed by markcowl** 2024-09-10 01:44 UTC
Labels: needs-area
