### ISSUE TITLE
[Bug][tcgc] getSdkUnion would merge underlying enum members to top level

### ISSUE THREAD

**Issue by MaryGao** [Azure/typespec-azure#379] opened 2024-03-07 09:50 UTC
**Describe the bug**
When we adopt to the latest tcgc our [two cases failed](https://github.com/Azure/autorest.typescript/blob/d78e698f87ffb97d16688852908292383aa3519f/packages/typespec-ts/test/modularUnit/type.spec.ts#L119-L174) and we found that 
- Sometimes the getSdkUnion could return correct isFixed value like Case 2 but sometimes it can't like Case 1
- Also for union of EnumA | EnumB tcgc would flatten all underlying enums into top level 

TCGC are supposed to provide consistant isFixed information, otherwise it would be a big issue for JS because RLC didn't adopt tcgc but Modular does. So it would introduce type inconsistancy between them and finally fails the compile process.

Also I think current behavior for prompting members to top level is debetable. It would lose the name info which may be useful for emitters.

### Case 1: Nullable enum
```
enum Color {
  Color1: 1,
  Color2: 2
}
model Test {
  color: Color | null;
}
op read(@body body: Test): void;
``` 

![image](https://github.com/Azure/typespec-azure/assets/9943211/4099ea27-591d-4781-86ba-234c3d83cefe)

### Case 2: EnumeA | EnumB

```
 enum LR {
  left,
  right,
}
enum UD {
  up,
  down,
}

model Test {
  color: LR | UD;
}
op read(@body body: Test): void;
```

![image](https://github.com/Azure/typespec-azure/assets/9943211/489ecfd2-488d-4c22-a015-d5d0adebaef2)

**Comment by tadelesh** [comment] 2024-03-07 10:20
TCGC get this info from two places, first is `isFixed` ([code](https://github.com/Azure/typespec-azure/blob/a15638510b0f8059b69b78e05cdc08a3ec0ef7a2/packages/typespec-azure-core/src/decorators.ts#L58)) from `@fixed` decorator, second is the `open` property in `UnionEnum` type ([code](https://github.com/Azure/typespec-azure/blob/a15638510b0f8059b69b78e05cdc08a3ec0ef7a2/packages/typespec-azure-core/src/helpers/union-enums.ts#L23)). I think current problem should mainly from losing information for hierarchy union.

**Comment by lirenhe** [comment] 2024-03-07 12:33
@MaryGao, in JS, do we have a workaround for this issue?

**Comment by MaryGao** [comment] 2024-03-07 13:39
> isFixed
I don't think we have a quick workaround here, currently we just fallback to tcgc dev.17 version.

**Comment by iscai-msft** [comment] 2024-03-07 20:33
Here we are only calling what `typespec` and `typespec-azure` are providing us, like @tadelesh said. Talked with @lmazuel and for case 1, it is by design that `isFixed` is still returning `False`. The tsp team will change the behavior of `isFixed` once everyone has moved to adopting "union with base type is extensible enum"

**Comment by lmazuel** [comment] 2024-03-07 20:50
Both your cases are by design and work as expected:

```
enum Color {
  Color1: 1,
  Color2: 2
}
```
is an extensible enum. We do have plan to switch this to fxed enum, when we can confirm all emitters are treating the union correctly

Flattening enum values is by design as well.

@MaryGao I'm worried to be honest of what "workaround" you would do here, since both are by designed. I'm closing this issue, and we can confirm this off-line.

**Comment by tadelesh** [comment] 2024-03-08 03:45
The inconsistency is come from the flatten. TCGC uses [`getUnionAsEnum`](https://github.com/Azure/typespec-azure/blob/a15638510b0f8059b69b78e05cdc08a3ec0ef7a2/packages/typespec-azure-core/src/helpers/union-enums.ts#L83) to see if a union is an enum, and this function does the judgement from the flattened elements view because TypeSpec type system, `UnionEnum` type could has child union or enum element. Since client type system could only has union or enum type, I made a fix to change back to union if union has union or enum variants, regardless of it is an enum with flatten view.

**Comment by tadelesh** [comment] 2024-03-12 05:26
JS has workaround for the inconsistency of whether is open for flattened union as enum.

**Closed** 2024-03-22 22:51 UTC
Labels: bug, TCGC, getAllModels
