### ISSUE TITLE
[Bug]: `SdkEndpointParamter.clientDefaultValue` should have value

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#989] opened 2024-06-12 03:59 UTC
### Describe the bug

`SdkEndpointParameter` extends `SdkModelPropertyBase` which has `clientDefaultValue` which should have value for `SdkEndpointParameter` (like `http://localhost:3000`). Right now, the value is in `SdkEndpointParameter.type.serverUrl`

### Reproduction

Parse a typespec spec, check the `SdkEndpointParameter` value

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by iscai-msft** [comment] 2024-06-24 20:33
this information is not on the `SdkEndpointParameter` itself, because we have made our design work fro both templated and non-templated endpoints. Instead, this information is in `templateArgs`, where if ther's a `.clientDefaultValue`, that information would be in the template arguments. Closing because this is by design

**Closed by iscai-msft** 2024-06-24 20:33 UTC
Labels: bug, lib:tcgc
