### ISSUE TITLE
[Feature Request] [tcgc] Provide example detail for operations if existing

### ISSUE THREAD

**Issue by MaryGao** [Azure/typespec-azure#396] opened 2024-03-11 10:00 UTC
Every language has the requirement to generate samples especially for mgmt SDKs and in M4 we have test modeler to help prepare example models and now I think TCGC is the proper place to ask for help.

I was wondering if TCGC could support to provide the example models both for short-term and long-term situation where we have in TypeSpec design.

**Short term:**
- Have `examples-directory` option in which we have JSON formmat examples 

**Long term**
- Have native support in typespec: https://github.com/microsoft/typespec/issues/2700

Refer
- https://github.com/Azure/typespec-azure/issues/118

**Comment by lmazuel** [comment] 2024-03-11 17:16
We should be consistent with what the Swagger emitter is doing, and it's indeed reading `examples-directory`. I think TCGC scope here would be read the option, and pre-load the right example and attach it to the right operation, so emitters do not have to do this folder logic work. Interpreting this example is quite specific per language after that.

**Comment by iscai-msft** [comment] 2024-06-24 17:36
duplicate of https://github.com/Azure/typespec-azure/issues/974

**Closed by iscai-msft** 2024-06-24 17:36 UTC
Labels: feature, lib:tcgc
