### ISSUE TITLE
[Bug][TCGC] Multiple instances of `OperationStatus` model definition

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#346] opened 2024-03-01 07:29 UTC
**Describe the bug**
This is a successor of #204 After fixing it, `OperationStatus` appears in the `context.modelsMap`. However, it seems that the `OperationStatus` instance in `context.modelsMap` is NOT the same as the one returned in `getLroMetadata`. So codes like below won't work:

```typescript
 function getInputModelForModel(m: Model): InputModelType | undefined {
    if (context.modelsMap!.has(m)) { // won't work because `m` is a different instance then the one in `modelsMap`.
       ...
 }
```

**To Reproduce**
- Try to parse the lro operation like the one in https://github.com/Azure/typespec-azure/blob/de0ebdac48d67adf07a78fd17abd534992e62476/packages/typespec-client-generator-core/test/public-utils.test.ts#L1377.
- Check the `OperationStatus` instances from `getLroMetadata` and `context.modelsMap`

**Expected behavior**
`OperationStatus` instance should be globally unique.

**Additional context**
![image](https://github.com/Azure/typespec-azure/assets/4516/247fe2dd-824f-4522-a551-61d6c6f92788)

Not sure if it's related to how `OperationStatus` is fetched inside `getLroMetadata`. I tried to debug, and it's from `getResourceLocationType`: https://github.com/Azure/typespec-azure/blob/de0ebdac48d67adf07a78fd17abd534992e62476/packages/typespec-azure-core/src/lro-helpers.ts#L1113 which is: https://github.com/microsoft/typespec/blob/8c7c76bf8e17e9ab2ad5a8bab6c3a8ba2d125de3/packages/rest/src/rest.ts#L562

**Comment by archerzz** [comment] 2024-03-05 09:18
After debugging, I think the problem is not because of there are multiple instance of the same `OperationStatus`. It's because of the metadata parsed by `getLroMetadata()` is different from what TCGC parsed.

![image](https://github.com/Azure/typespec-azure/assets/4516/fa7000ca-4681-4a14-a8ae-d524a9f476d5)
The above is the `OperationStaus` parsed by `getLroMetadata()`. As you can see, it's name is `OperationStatus`.

![image](https://github.com/Azure/typespec-azure/assets/4516/7e7d387b-ac09-4680-b7fb-5b129825f6f9)
This is what the corresponding metadata in TCGC. Its name is `ResourceOperationStatus`, and its `sourceModel` property is the same as the one parsed by `getLroMetadata`.

`ResourceOperationStatus` **is** a `OperationStatus`: https://github.com/Azure/typespec-azure/blob/4b262972565a65856d088ca160858158072a7428/packages/typespec-azure-core/lib/models.tsp#L48-L54

Now the problem is how we get the two different sybmols.

**Comment by tadelesh** [comment] 2024-03-05 09:37
The root cause should be https://github.com/Azure/typespec-azure/issues/311#issuecomment-1965707209

**Comment by iscai-msft** [comment] 2024-06-24 17:31
Switching to `envelopeResult` should've fixed the issue, @archerzz I'm going to close this issue, if it's still an issue, can you reopen? Thank you!

**Closed by iscai-msft** 2024-06-24 17:31 UTC
Labels: bug, lib:tcgc
