### ISSUE TITLE
[Bug][TCGC]: `apiVersions` of subclients can be undefined

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#1089] opened 2024-06-27 07:04 UTC
### Describe the bug

See this spec: https://github.com/Azure/autorest.csharp/blob/5c4fa0277ee7087fbd3a55ef629ab190405d18bd/test/TestProjects/sdk/newprojecttypespec/Azure.NewProject.TypeSpec/Azure.NewProject.TypeSpec.tsp#L203

`Demo` is a subclient, and its `apiVersions` is `undefined`. I think it should be an empty array.
![image](https://github.com/Azure/typespec-azure/assets/4516/b54f8a54-4c3c-4992-acf1-3d87317c049b)

### Reproduction

Just parse the spec in the link above.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment] 2024-06-27 07:30
for service without versioning, we always return undefined.

**Comment by iscai-msft** [comment] 2024-08-07 20:21
closing since this is by design, @archerzz please reopen if this is still an issue

**Closed by iscai-msft** 2024-08-07 20:21 UTC
Labels: bug, lib:tcgc
