### ISSUE TITLE
Provide a decorator to indicate to the generator that service's response content stream should not be buffered

### ISSUE THREAD

**Issue by annelo-msft** [Azure/typespec-azure#820] opened 2024-05-10 20:33 UTC
### Clear and concise description of the problem

In .NET Azure clients, we [buffer response content](https://azure.github.io/azure-sdk/general_azurecore.html#response-downloader-policy) by default in the client pipeline.  This feature can be turned off for service methods that return a network stream to the end user.  An example of this in a DPG client is shown [here](https://github.com/Azure/autorest.csharp/blob/6f4e894f01d27abf35f0bac19ba56a055300f59a/test/TestServerProjectsLowLevel/body-file/src/Generated/FilesClient.cs#L244).

@m-nash has shared that TypeSpec does not currently provide a way to indicate to the generator that is should write a service method with response content buffering disabled.  We have requested this feature from the generator here: https://github.com/Azure/autorest.csharp/issues/4693

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by iscai-msft** [comment] 2024-06-24 18:54
duplicate of https://github.com/Azure/typespec-azure/issues/614

**Closed by iscai-msft** 2024-06-24 18:54 UTC
Labels: feature, lib:tcgc
