### ISSUE TITLE
final-state-via could not be modeled in tsp

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#105] opened 2024-01-10 09:38 UTC
e.g.,
```typescript
delete is ArmResourceDeleteAsync<
    CertificateProfile,
    BaseParameters<CertificateProfile>,
    ArmAsyncOperationHeader
  >;
```
generated swagger, pay attention to `final-state-via`
```json
    "delete": {
        "operationId": "CertificateProfile_Delete",
        ...
        "x-ms-examples": {
          "Delete Certificate Profile": {
            "$ref": "./examples/CertificateProfile_Delete.json"
          }
        },
        "x-ms-long-running-operation-options": {
          "final-state-via": "location"
        },
        "x-ms-long-running-operation": true
      }
    },
```

**Comment by markcowl** [comment] 2024-01-11 19:11
No, this would violate ARM Swagger rules

**Comment by markcowl** [comment] 2024-01-11 19:17
We are very specifically *not* changing the emitted swagger based on changes to the headers - clients processing ARM APIs follow a set pattern.  We are only encoding additional information for use by TypeSpec emitters.

**Comment by markcowl** [comment] 2024-01-11 19:35
@tadelesh I think the right thing here is to add some linting rules that prevent replacing these values with headers that don't include Location.

There is some flexibility around combining Azure-AsyncOperation with Location, but removing Location is *definitely* not allowed for PATCH, POST, and DELETE LROs

The thought is that ARM LROs based on Swagger will not actually care about the options values, so even though Azure-AsyncOperation is better to use, if present, it is required by RPC that the operation *can* be resolved via the Location header for these.

**Comment by tadelesh** [comment] 2024-01-16 06:02
AFAIK, some languages' sdk will relay on lro options to generate code. I just want to make sure the swagger emitter from typespec is identical with the original swagger. I have no idea about this will cause breaking change if we change the options.

**Comment by markcowl** [comment] 2024-01-17 04:39
As with other things, APIs that do not follow the ARM RPC should not be represented in library templates - if changing lro options causes a breaking change for ARM clients, then IMO, these operations should be represented at a lower level.

**Comment by markcowl** [comment] 2024-01-18 00:24
- Do we need final-state-via for mgmt clients?  
   - What is the impact if ithis is removed?
- Do we need this for terraform, CLI, or PS?
   - What is the impact if it is removed.

**Comment by tadelesh** [comment] 2024-01-18 07:22
For Go, we will use it in polling option, see [code](https://github.com/Azure/azure-sdk-for-go/blob/ddf768e798ef5480e85a27ff2711a2feb5c811cb/sdk/resourcemanager/elasticsan/armelasticsan/elasticsans_client.go#L61). And it will be used in the following polling process. Though Go have fallback logic if this option is empty. But I have no confidence to remove it. cc: @jhendrixMSFT

**Comment by weidongxu-microsoft** [comment] 2024-01-18 07:59
Java do not use `final-state-via`

**Comment by live1206** [comment] 2024-01-19 02:13
.NET needs it to get the final request Uri, details can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/2d0ddafbd4cb091b193e6ba84ab4a6384639a53f/sdk/core/Azure.Core/src/Shared/NextLinkOperationImplementation.cs#L239).
And we had a arch-board review meeting regarding cross-language LRO rehydration, we are still discussion about the content of rehydration id. For now, .NET put `final-state-via` as needed content.

**Comment by msyyc** [comment] 2024-01-25 08:44
Python LRO polling needs it to get final request url:
- generated SDK code: https://github.com/Azure/azure-sdk-for-python/blob/530f71581044ca21faa7cd0773d30210cc37e01f/sdk/hybridcontainerservice/azure-mgmt-hybridcontainerservice/azure/mgmt/hybridcontainerservice/operations/_provisioned_cluster_instances_operations.py#L535
- azure-core: https://github.com/Azure/azure-sdk-for-python/blob/530f71581044ca21faa7cd0773d30210cc37e01f/sdk/core/azure-core/azure/core/polling/base_polling.py#L298-L320

**Comment by MaryGao** [comment] 2024-01-25 12:27
JS would use `final-state-via` to identify the resource location and check [code](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-lro/src/http/operation.ts#L57-L76) for more details.

**Comment by msyyc** [comment] 2024-02-26 06:27
It seems work now for typespec-autorest: https://github.com/Azure/typespec-azure/issues/310#issue-2153348800

**Comment by lmazuel** [comment] 2024-03-11 16:49
Side note. Python honors `final-state-via` only for POST operations, and ignored it for everything else. Last time we did an experiment to add the PUT  support, we had to revert it because most of the spec were plain wrong.
This option has been misundertood by a lot of service teams, and I'm quite confident a lot of Swagger uses it incorrectly. To me it's counterproductive to try to reproduce the Swagger here, and we should confirm with service teams that they used it correctly, otherwise we would just continue spreading incorrect values.

**Comment by allenjzhang** [comment] 2024-04-19 18:31
- modify `getLroMetadata` to support standard ARM `final-state-via` pattern values
- Add `@finalStateVia` decorator in `Azure.Core` to allow override.
- Add `@finalStateSchema` decorator in `Azure.Core` to allow override schema

**Comment by markcowl** [comment] 2024-05-07 02:42
@allenjzhang 
- getLroMetadaata already supports the standard values for final-state-via
- There are already decorators to override the lro return type and final-state-via, which impact not just the values, but the actual mechanism used.  If we want to produce different values in autorest despite what is encoded in a spec, these decorators (@finalStateVia, @finalStateSchema) should go in TCGC

**Comment by markcowl** [comment] 2024-06-06 18:56
**Describe the breaking change**
This will update Swagger generated from TypeSpec to include 'final-state-schema' and adds validation for that displayed options match the underlying API and lro decorators.

**Back-compat design to avoid immediate breaking**
Added mechanisms to choose a particular final-state-via when multiple are possible and valid, overriding the default precedence rules. Also, implemented a configuration toggle, so data plane specs can be exempted from changes.

**Link to detailed breaking design**
Link:

**Impact**
This change affecting:

- [x] ARM
- [ ] Data-plane
- [x] Existing specs: approx. # of service/spec impacted: TBD
- [x] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: June

**Additional information**
Will include links to typespec-next PRs

**Comment by markcowl** [comment] 2024-06-12 23:03
Fixed

**Closed by markcowl** 2024-06-12 23:03 UTC
Labels: external:mgmt
