### ISSUE TITLE
[Bug]: Auto-calcluated path for `StandardResourceOperations.ResourceAction` is different when having operation renaming in client.tsp

### ISSUE THREAD

**Issue by MaryGao** [Azure/typespec-azure#1021] opened 2024-06-17 05:26 UTC
### Describe the bug

This is case in LoadTesting([spec here](https://github.com/Azure/azure-rest-api-specs/blob/0aa7ac99172545656aaae911ce13ad572ff0fac1/specification/loadtestservice/LoadTestService/client.tsp#L58-L59)) and found in JS codegen([here](https://github.com/Azure/autorest.typescript/pull/2583#discussion_r1642194766)). The auto-calculated route is different after adding customization in `client.tsp`.

[playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXLfN2MtY2xpZW50LWdlbmVyYXRvcshtCnVzaW5nIEHENC5Db3JlO9ESLlRyYWl0c8gZVHlwZVNwZWMuUmVzdNEVSHR0cNEVVukBCsgbT3BlbkFQSc9t5QCkR%2BgAo8V9OwoKLy8gLcQBIEhlcmUgaXMgbWFpbi50c3DFFwpAc2VydmljZSh7CiAgdGl0bGU6ICJDb250b3NvIFdpZGdldCBN5wEmLAp9KQpA5wGZZWQoxycuxifHJugAr3MpCm5hbWVzcGFjZSDVKuQAnSoqIFRoySDPcSDnAJwgx3MuICovCmVudW0gyGQg5AC2xEXHESAyMDIyLTA4LTMxxCwgIEB1c2VEZXBlbmRlbmN5KOsBl8hDLnYxXzBfUHJldmlld18yKQogIGDJRjBgLAp9CgpAZG9jKCJGaWxlIGluZm8iKQpA6AJDKCJmaWxlcyIpCm1vZGVsIMQlSW5mb%2BUAmsY4TmFtZSBvZiB0aGUgxC0uIsRlQGtlecQHdmlzaWJpbGl0xA7EH8QvOiBzdHLlAfF9CgppbnRlcmbkAUdGb8xYU3RvcCB0ZXN0IHJ1biBiecoMSWTHZG9w5AINaW9uSWQoIkxvYWRUZXN0UnVuX8Q8xwzFKnPETGlzIFN0YW5kYXJkUucA30%2FIQXPkArHFE0FjxBA86ADpLCB7fSzpAPfEDj7lALbxAnhjdXN0b21pesVPIGluIOYDVesCi8YR5QKK5AI7OiDsALPmAt8iLOQAreYCFzr2AlflAqbqATTHP%2BoAyeUBQuQA8Mca5ACcRm9vLsQT5AC6&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fresource-manager%22%5D%7D%7D)
- main.tsp
```
interface Foo {
  @doc("Stop test run by test run Id.")
  @operationId("LoadTestRun_StopTestRun")
  stop is StandardResourceOperations.ResourceAction<FileInfo, {}, FileInfo, {}>;
}
```
The path we got is `/files/{fileName}:stop`.

- client.tsp
```
@client({
  name: "LoadTestRunClient",
  service: Contoso.WidgetManager,
})
interface TestRunOperations {
  stopTestRun is Foo.stop;
}
```
The path we got is `/files/{fileName}:stopTestRun`.

### Reproduction

[playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXLfN2MtY2xpZW50LWdlbmVyYXRvcshtCnVzaW5nIEHENC5Db3JlO9ESLlRyYWl0c8gZVHlwZVNwZWMuUmVzdNEVSHR0cNEVVukBCsgbT3BlbkFQSc9t5QCkR%2BgAo8V9OwoKLy8gLcQBIEhlcmUgaXMgbWFpbi50c3DFFwpAc2VydmljZSh7CiAgdGl0bGU6ICJDb250b3NvIFdpZGdldCBN5wEmLAp9KQpA5wGZZWQoxycuxifHJugAr3MpCm5hbWVzcGFjZSDVKuQAnSoqIFRoySDPcSDnAJwgx3MuICovCmVudW0gyGQg5AC2xEXHESAyMDIyLTA4LTMxxCwgIEB1c2VEZXBlbmRlbmN5KOsBl8hDLnYxXzBfUHJldmlld18yKQogIGDJRjBgLAp9CgpAZG9jKCJGaWxlIGluZm8iKQpA6AJDKCJmaWxlcyIpCm1vZGVsIMQlSW5mb%2BUAmsY4TmFtZSBvZiB0aGUgxC0uIsRlQGtlecQHdmlzaWJpbGl0xA7EH8QvOiBzdHLlAfF9CgppbnRlcmbkAUdGb8xYU3RvcCB0ZXN0IHJ1biBiecoMSWTHZG9w5AINaW9uSWQoIkxvYWRUZXN0UnVuX8Q8xwzFKnPETGlzIFN0YW5kYXJkUucA30%2FIQXPkArHFE0FjxBA86ADpLCB7fSzpAPfEDj7lALbxAnhjdXN0b21pesVPIGluIOYDVesCi8YR5QKK5AI7OiDsALPmAt8iLOQAreYCFzr2AlflAqbqATTHP%2BoAyeUBQuQA8Mca5ACcRm9vLsQT5AC6&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fresource-manager%22%5D%7D%7D)
The http path should be the same no matter we have client.tsp or not.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markcowl** [comment] 2024-06-17 18:42
This is by design, as if you don't apply an `@action` decorator, the final path of the action will match the name of the operation.  Although, arguably, this would be a good candidate for a linter warning

**Comment by qiaozha** [comment] 2024-06-20 12:58
@markcowl  I think the root cause for this issue is the keyword `is` has two different kind of meanings here. in the main.tsp, `is` is being used to define an operation, and in the client.tsp, `is` is being used to rename an operation. I feel like we should figure out a way to split the meaning here. Not sure we have any plan to redesign this ?

**Comment by markcowl** [comment] 2024-06-20 16:53
@qiaozha It should not be the case that 'is' is being used just to rename operations.  In this case, @clientName should be able to handle the issue.  Generally, in the client.tsp, 'is' is used for two reasons:
- regrouping operations 
- redefining the operation signature for clients (for example, creating options bags)
In the case of POST actions, the issue is that the last segment of the operation path comes from the operation name, unless it is explicitly set using @action .  If we had a linting rule that detected the change of operation path through use of 'is',  then authors of client.tsp could be warned away from patterns that change the operation path.

**Comment by markcowl** [comment] 2024-06-21 16:47
resolving as duplicate of https://github.com/Azure/typespec-azure/issues/297

**Closed by markcowl** 2024-06-21 16:47 UTC
Labels: needs-area
