### ISSUE TITLE
[TCGC] Provide `SdkApiVersionParameter` as part of `SdkParameter`

### ISSUE THREAD

**Issue by archerzz** [Azure/typespec-azure#948] opened 2024-06-04 05:56 UTC
### Clear and concise description of the problem

`api-version` is defined as metadata of the whole service, see an example: https://github.com/Azure/azure-rest-api-specs/blob/a5a01e06ffbbc0b0c945cb58fe769d19a4f93af4/specification/devcenter/DevCenter/main.tsp#L34

```typespec
@doc("DevCenter service")
@versioned(APIVersions)
namespace DevCenterService;
```

- It would be better if we could provide `SdkApiVersionParameter` as part of `SdkParameter` instead of `SdkMethodParameter`
- In csharp (and probably some other languages), `api-version` is part of client parameters. However, certain service demands that we could provide `api-version` as method parameter so that users can override it. In that case, if we always provide `api-version` as method parameter, then we cannot differentiate where we should put `api-version` in the generated codes.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For feature request in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Read the [docs](https://azure.github.io/typespec-azure/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by iscai-msft** [comment] 2024-06-24 19:56
Currently we use `.isApiVersion` information on parameters for this. This is because api version can be query, path, header etc. So this is by design. If you have an idea, can you go ahead and reopen the issue? I'm closing it because I believe this is by design. Thanks!

**Closed by iscai-msft** 2024-06-24 19:56 UTC
Labels: feature, lib:tcgc
