### ISSUE TITLE
[Bug]: sdkPackage.models is missing Error type

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/typespec-azure#1412] opened 2024-08-22 15:25 UTC
### Describe the bug

Model `FailedLockToken` contains field `error` of type `Azure.Core.Foundations.Error` but it's missing in the array of model types. As a result, the type isn't emitted during codegen.

### Reproduction

Build https://github.com/Azure/azure-rest-api-specs/tree/main/specification/eventgrid/Azure.Messaging.EventGrid with tcgc version `0.44.3`

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tadelesh** [comment] 2024-09-29 06:34
it is by design. with current tcgc logic, all azure core model will be filtered in `sdkPackage.models` if `filter-out-core-models` set to true. but the property type used in `FailedLockToken` will still refer to that model. @iscai-msft i'm thinking of not do any filtering for tcgc output, leave them to emitter is more flexiable.

**Comment by iscai-msft** [comment] 2024-10-07 15:13
yeah i'm starting to agree that filtering out core models might be more effort than it's worth. Let me bring this up during discussions on wednesday since this will require emitters to modify their own logic

**Comment by tadelesh** [comment] 2024-10-16 06:42
We have discussed this issue in DPG sync ups. We all agree that languages' emitter should already deal with the core model's in emitter's logic, so it is safe to remove the filtering logic in TCGC. @jhendrixMSFT , I'm wondering if Go has filtering logic for core models? The most common scenario is the `ErrorResponse` model. With current TCGC logic, `sdkPackage.models` will not contain that model, but after change, it will.

**Comment by jhendrixMSFT** [comment] 2024-10-16 13:56
When you say `ErrorResponse` model that sounds different from `Azure.Core.Foundations.Error`. While we can treat these the same, shouldn't services be using `Azure.Core.Foundations.Error` instead of defining their own error models (at least when the expectation is for a core error to be returned)?

**Comment by tadelesh** [comment] 2024-10-16 14:33
Sorry, I do mean `Azure.Core.Foundations.Error`. It will be in `sdkPackage.models` if we do not filtering core models, and Go needs to ignore generating then.

**Comment by jhendrixMSFT** [comment] 2024-10-16 14:45
Yep we can filter these out (I think we already do).

**Closed** 2024-11-04 10:05 UTC
Labels: bug, lib:tcgc
