### ISSUE TITLE
[Bug]: TCGC getClientNameOverride returns an object (instead of string or null)

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/typespec-azure#699] opened 2024-04-19 03:34 UTC
### Describe the bug

```ts
export declare function getClientNameOverride(context: TCGCContext, entity: Type): string | undefined;
```

but it returns an object when the issue happens
![image](https://github.com/Azure/typespec-azure/assets/53292327/5912db96-4a89-4e49-a479-f272f7190535)

### Reproduction

loadtesting 
https://github.com/Azure/azure-rest-api-specs-pr/blob/c4b80c74909bf593825e29ce7ff459decba35efd/specification/loadtestservice/LoadTestService/tspconfig.yaml

PR https://github.com/Azure/azure-rest-api-specs-pr/pull/17749

operation is
```ts
createOrUpdateTest is StandardResourceOperations.ResourceCreateOrUpdate<Test>;
```

they also have a
```ts
@@clientName(Azure.Core.Foundations.ResourceBody.resource, "body");
```
in routes.tsp, not sure if related.

call to `getClientNameOverride` is on the ModelProperty of the `Test` model.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mitsha-microsoft** [comment] 2024-04-19 05:54
Hi @weidongxu-microsoft ,
I am from the load testing team. Is this bug present in the version we install via npm as well, as I am not able to generate C# SDKs for my APIs

**Comment by weidongxu-microsoft** [comment] 2024-04-19 05:58
@mitsha-microsoft 

It likely present in the csharp emitter as well. But you may want to contact csharp dev on this, as it may not be the only cause.
(you can try comment out the `@@clientName(Azure.Core.Foundations.ResourceBody.resource, "body");`, if emitter works without this line in routes.tsp, likely this is the cause)

I'm Java and this is the only problem on Java emitter.

**Comment by tadelesh** [comment] 2024-04-19 10:23
I could not reproduce locally. You mean call `getClientNameOverride` for the body parameter will return object?

**Comment by tadelesh** [comment] 2024-04-22 05:20
@timotheeguerin in tcgc, the decorator function could not get `string` value, but a decorator object (minimum tsp case [here](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3ytjLWNsaWVudC1nZW5lcmF0b3LINgp1c2luZyBUeXBlU3BlYy5IdHRwO9AVUmVzdNEVVukAqMgbQcR5LkNvcmXSEi5UcmFpdHPPGeUAlUfoAJTHOwpAdXNlQXV0aCgKICBBcGlLZXnEDjzGC0xvY2F0aW9uLmhlYWRlciwgImFwaS1rZXkiPiB8IE%2FEKjLFL1sKICAgIHvFBiAg5AEJOscfRmxvd%2BQAxy5pbXBsaWNpdCzHJWF1dGhvcml6xWFVcmw6ICLkAcBzOi8vbG9naW4uY29udG9zby5jb20vY29tbW9uL2%2FENTIvdjIuMC%2FIQGUiyFJzY29wZXM6IFvJSXdpZGdldM1KLmRlZmF1bHQiXcY3fQogIF0%2BCikKQHNlcnZpY2Uo5ADGdGl0bGU6ICJDxjogV8VJIE1hbmFnZXIiLAp9xzFlcuQBOSJ7ZW5kcG9pbnR9x3TlAJXQP0FQSXPFGcRjICAvKiogClN1cOQCS2VkyCVT5gCHcyDIU3MgKHByb3RvY29sIGFuZCBob3N0bmFtZSwgZm9yIGV4YW1wbGU6CukA9GVzdHVzLmFwaS7yAP8pLgogKi%2FFfshfOiBzdHJpbmfkAJh95AEI5wMUZWQo5wC%2FLuYAmucA%2FegCjHMpCuQAhnNwYWNlINUqOwoK5ADjVGjJIO8BSCDnAXMgx3Mu5ACcZW51bSDIZOUBKsRFxxEgMjAyMi0wOC0zMcQsICDkAr9EZXBlbmRlbmN5KOsDBMhDLnYxXzBfUHJldmlld18yKQogIGDJRjBgLAp9CkByZXNvdXJjZSgidGVzdHMiKQptb2RlbCBUZXN05QCDQGtleQogIGlk6AEuOwoKICBwcm9wyhF9CgpvcCBjcmVhdGVPclVwZGF0ZcVBaXMgU3RhbmRhcmRSx2lPcOQDhuUAn8gTQ805PMQ6PuQDoEDmBE5OYW1l7ADfRm91bmTPQ0JvZHku6ADMLCAiYm9keSIpOwo%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-core%2Fall%22%5D%7D%7D)). i'm wondering if it is a tsp bug?
![image](https://github.com/Azure/typespec-azure/assets/1726438/dfacd49a-7646-4816-ad5a-da44fd48b534)

**Comment by timotheeguerin** [comment] 2024-04-22 18:40
Is this only happening in that specific case? I was trying with the @doc decorator instead and that seems to work fine with the playground you shared

**Comment by tadelesh** [comment] 2024-04-23 06:54
i could repro with this [tsp](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdMwZYXp1cmUtdG9vbHMvyCUtY2xpZW50LWdlbmVyYXRvci1jb3JlIjsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN0yBVBxF4uQ8VPR8hOLkNvcmU7Cgptb2RlbCBSZXNvdXJjZUJvZHk8yA0%2BIHsKICBAYm9keQogIHLHFjrJLTsKfQoKQHBvc3QKb3AgZG%2FJOSBleHRlbmRzIHt9PiguLuQAjdNeKTogdm9pZDsKCkBA5gDsTmFtZSjMLS7IdSwgIuQAhyIp6QCyVGVzdOUAoGlkOiBzdHJpbmc7CiAgcHJvcMoQfQrkAJp0xCtpc%2BQAosQ2PjsK&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-core%2Fall%22%5D%7D%7D).
![image](https://github.com/Azure/typespec-azure/assets/1726438/ec668edf-5b0c-4ea6-aca8-a26ba02b6bdb)

**Comment by timotheeguerin** [comment] 2024-04-23 14:37
ok so the trigger is augmenting a templated type with `@clientName` but what is weird is it doesn't apply to other decorators

**Comment by timotheeguerin** [comment] 2024-04-23 14:39
hhm actually happens to `@extension` as well. So seems like maybe the compiler decorators work for some reason but libraries don't

**Comment by timotheeguerin** [comment] 2024-04-23 15:37
Filed this https://github.com/microsoft/typespec/issues/3211 and fix here https://github.com/microsoft/typespec/pull/3212

**Comment by timotheeguerin** [comment] 2024-04-24 15:24
@weidongxu-microsoft @tadelesh can you confirm this has been fixed with latest compiler and so can we close this issue?

**Comment by tadelesh** [comment] 2024-04-25 09:49
@timotheeguerin I've tested in TCGC and it has been fixed. Thank you so much.

**Closed by tadelesh** 2024-04-25 09:49 UTC
Labels: bug, needs-triage
