### ISSUE TITLE
Type changed for `envelopeResult` from `getLroMetadata`

### ISSUE THREAD

**Issue by tadelesh** [Azure/typespec-azure#311] opened 2024-02-26 08:39 UTC
When calling `getLroMetadata` for `createOrUpdate` for the [template resource](https://github.com/Azure/autorest.python/blob/2f5b207a2ea1046521c086155c3711cadc830c79/packages/typespec-python/test/azure/specification/mgmt/sphere/product.tsp#L18), I got `logicResult` with right TypeSpec type `Product`, but `envelopResult` with a wrong calculated TypeSpec type `ProxyResource` as follow screenshot.
After some investigation, I found the type is changed after calling `getEffectiveModelType` [here](https://github.com/Azure/typespec-azure/blob/00f500c4ba7cf3fcae628bfbad651c87695fc0a5/packages/typespec-azure-core/src/lro-info.ts#L102). Since the resource model has a path parameter, so it will enter the logic of finding a naming model which is same to the resource model without this path parameter (filter logic). When it has no exactly same model, it will also find a model that is same with it with the same filter logic, then the final result will fall to the original model. But after the complicated process, the type has totally changed and the naming info lost, it make the emitter hard to distinguish if it is the same resource model. Either fix the `getEffectiveModelType` logic for templated model or change the logic of `getLroMetadata` coudl resolve it. I don't know whether it should be opened as a core compiler problem or a `getLroMetadata` problem, If wrong place, I could move it.
![image](https://github.com/Azure/typespec-azure/assets/1726438/7bb7420e-7a72-4f30-9ecb-e5faf6be032e)

**Comment by markcowl** [comment] 2024-02-26 20:31
I think this is by design, the finalEnvelopeResult (which matches the finalResult) is the value that *should be used by emitters.

**Comment by tadelesh** [comment] 2024-02-27 03:08
Let me explain more clearly. The main problem here is for the following TypeSpec, when we call `getEffectiveModelType`, we will get the result type with same structure with `Product`, but wrong name `ProxyResource`. I suppose it should return the type of `Product`.
```
model Product is ProxyResource<ProductProperties> {
  @doc("Name of product.")
  @pattern("^[\\w][\\w\\s]{1,48}[\\w]$|^\\.default$|^\\.unassigned$")
  @key("productName")
  @path
  @segment("products")
  name: string;
}
```

**Comment by tadelesh** [comment] 2024-03-05 07:56
> Let me explain more clearly. The main problem here is for the following TypeSpec, when we call `getEffectiveModelType`, we will get the result type with same structure with `Product`, but wrong name `ProxyResource`. I suppose it should return the type of `Product`.
> 
> ```
> model Product is ProxyResource<ProductProperties> {
>   @doc("Name of product.")
>   @pattern("^[\\w][\\w\\s]{1,48}[\\w]$|^\\.default$|^\\.unassigned$")
>   @key("productName")
>   @path
>   @segment("products")
>   name: string;
> }
> ```

@timotheeguerin do you think it is a bug for `getEffectiveModelType`?

**Comment by markcowl** [comment] 2024-09-10 01:42
This should be handled by the fix here: https://github.com/Azure/typespec-azure/pull/1416

Closing as duplicate

**Closed by markcowl** 2024-09-10 01:42 UTC
Labels: bug, lib:azure-core
