### ISSUE TITLE
[TCGC] [ARM]  Expected client code on definition `model UserAssignedIdentities is Record<UserAssignedIdentity>;` 

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/typespec-azure#825] opened 2024-05-11 04:43 UTC
`typespec-azure-resource-manager` changed the defnition for `UserAssignedIdentities` in version `0.42`, from `userAssignedIdentities?: Record<UserAssignedIdentity>;`([code](https://github.com/Azure/typespec-azure/blob/4c7a78aeb2c4e75020568a6fb57fd8505d839f5b/packages/typespec-azure-resource-manager/lib/arm.foundations.tsp#L398) ) to `model UserAssignedIdentities is Record<UserAssignedIdentity>;`([code](https://github.com/Azure/typespec-azure/blob/bb338afd7c124c586d4c105475cdb3da1b216b17/packages/typespec-azure-resource-manager/lib/common-types/managed-identity.tsp#L33-L37))

Link Bug https://github.com/Azure/typespec-azure/issues/824

For `model A is Record<>` case, TCGC will return model `A` with additional property, this will be potential breaking changes in Mgmt plane, as current  generated code based on swagger will use `Map` directly, instead of model with additional properties. I think we should align with the current generated code, otherwise there will be many breaking changes. See current code: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/maps/azure-resourcemanager-maps/src/main/java/com/azure/resourcemanager/maps/models/ManagedServiceIdentity.java#L43-L45

To solve this:
- One solution is to have TCGC do special handling for `UserAssignedIdentities` to return it as `Map` directly. `common-types` have similar [definition](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v3/managedidentity.json), but previously M4 seems consider it as dictionary.
- Another solution is to let ARM change the definition back.

**Comment by tadelesh** [comment] 2024-05-11 05:15
I believe it should be fixed in arm typespec library. cc: @allenjzhang

**Comment by msyyc** [comment] 2024-05-13 07:37
Python has similar issue, too.

**Comment by timotheeguerin** [comment] 2024-05-13 15:58
This was changed to keep TypeSpec in sync with the common-types.json which we cannot break https://github.com/Azure/azure-rest-api-specs/blob/b627f6cb13b1d596e7329c6d7aae415519a373c2/specification/common-types/resource-management/v5/managedidentity.json#L9

**Comment by allenjzhang** [comment] 2024-05-13 16:13
Feels like TCGC interprets model references slightly different than autorest with swagger. I wonder if this is a wider problem that hasn't surfaced but exposed now with MPG work.

**Comment by allenjzhang** [comment] 2024-05-13 21:23
Questions:
  autorest generated SDK from swagger with $ref to v4/5, does it generate `UserAssignedIdentities`?

- If Yes, it would be right to change the behavior for MPG to generate that as well, so no breaking change switching from autorest to MPG.
- If No, autorest must have done some collapsing to skip `UserAssignedIdentities`. Therefor similar logic should be adopted in TCGC.

**Comment by ArcturusZhang** [comment] 2024-05-14 01:06
I assume we should be achieving "to keep the generated SDK unchanged after switched to typespec".

Swagger has a shortage that it cannot write different expressions for "a model with additional properties but no known properties", or "a pure dictionary", because these two things are the same from json's perspective, which is the thing swagger is representing.

And speaking of "keeping swagger common-types unchanged", I think it does not have to be as precisely as "it cannot change in a single character", I think it could be fine if the schema it represents is not changed.

It is an advantage that typespec now can express differently from the two different SDK APIs (models with additional properties and dictionaries), we should not give it up.

Therefore in order to keep our SDK unchanged - and the swagger is "unchanged" originally with some minor representation change, we have the following options:
1. change how typespec comprehends `model Foo is Record<Foo>`, because intuitively this means this model is a dictionary/record, and it should not allow other properties. We change its semantic meaning and stop using this to represent a model with additional properties, and let the compile give errors when other properties are added to this model.
2. let TCGC do the same thing as modeler v4 has done - when it sees a model with additional properties but no other known properties, it gives the downstream a record as if they write a `Record<T>` directly. But I think this is unacceptable with similar reason that we have to add constraints to unions as enums (`union Foo { "a", "b" }`). It changes from a type to a completely unrelated type when something not breaking is applied to the schema (in this case, a new property is added to the model).
3. the simplest solution, we just change how we write the resourcemanager typespec. We change the `model XXX is Record<T>` to `alias XXX = Record<T>`. This might not produce exactly the same swagger as before but I think maybe something could be done to the openapi emitter to have it? Or does it really matter the representation changes in swaggers? Because the purpose of existence of typespec is to let us get more information during sdk generation, and swagger should be as a generated public API, we will never use swaggers to generate SDK code any more when everything is ready.

**Comment by haolingdong-msft** [comment] 2024-05-15 03:16
> can you explain what you would have been doing here in openapi and why this is different.

@timotheeguerin 
When generating mgmt SDK from TypeSpec directly, `model UserAssignedIdentities is Record<UserAssignedIdentity>;` will be interpreted as a Model named `UserAssignedIdentities` which has `additionalProperties` by TCGC, [code](https://github.com/Azure/autorest.java/blob/main/typespec-tests/src/main/java/com/cadl/armresourceprovider/models/UserAssignedIdentities.java)
```java
public final class ManagedServiceIdentity {
    /*
     * The identities assigned to this resource by the user.
     */
    @JsonProperty(value = "userAssignedIdentities")
    private UserAssignedIdentities userAssignedIdentities;
}

public final class UserAssignedIdentities {
    /*
     * The set of user assigned identities associated with the resource. The userAssignedIdentities dictionary keys will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}. The dictionary values can be empty objects ({}) in requests.",
     * 
     * Additional properties
     */
    @JsonIgnore
    private Map<String, UserAssignedIdentity> additionalProperties;
}
```

But previously generating from swagger, Modular4 will interprete the swagger as `Map`. [code](https://github.com/Azure/autorest.java/blob/5324fdb5abc9b21eb0a9ecc9f838b67e3d202804/typespec-tests/src/main/java/com/cadl/armresourceprovider/models/ManagedServiceIdentity.java#L41)
```java
@Fluent
public final class ManagedServiceIdentity {
    /*
     * The identities assigned to this resource by the user.
     */
    @JsonProperty(value = "userAssignedIdentities")
    @JsonInclude(value = JsonInclude.Include.NON_NULL, content = JsonInclude.Include.ALWAYS)
    private Map<String, UserAssignedIdentity> userAssignedIdentities;
}
```

To solve this:
- we either have TCGC to handle it similar as M4, i.e. to model `model UserAssignedIdentities is Record<UserAssignedIdentity>;` as `dict` type.
- or change the ARM typespec definition back.

**Comment by tadelesh** [comment] 2024-05-16 00:23
add a [playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXIiOwoKdXNpbmcgVHlwZVNwZWMuSHR0cDvQFVJlc3TRFVbpAKnIG0HEZS5Db3JlzhJSx3dNxnY7Cgptb2RlbCBFbXB0eU3EC1dpdGhBZGRpdGlvbmFsUHJvcGVydGllcyBpcyBSZWNvcmQ8c3RyaW5nPjvRPCB7fchRVGVzdCB7CiAgcHJvcDE60TvGGTI633rEesgtMzoge33IDTTMOjsKfQoKLy8gcm9vdMQeYmxlbSBoZXJl5AC1Zm9yIHN3YWdnZXLEJOQBiCBvZsVFMSBhbmTFCjIgYXJlIHNhbWXQJDPJJDTNJMRX6AHULCB0aGV5IGhhdmUgZGlmZmVyZW50xR4K&e=%40azure-tools%2Ftypespec-autorest&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-resource-manager%2Fall%22%2C%22%40typespec%2Fhttp%2Fall%22%2C%22%40azure-tools%2Ftypespec-azure-core%2Fcanonical-versioning%22%2C%22%40azure-tools%2Ftypespec-azure-core%2Fall%22%5D%7D%7D) to show the root cause.

**Comment by timotheeguerin** [comment] 2024-05-16 17:30
1. Check with ARm Team what `UserAssignedIdentities` is meant for and if they might add known properties in the future
2. If not convert back to `alias`
3. To resolve inconsitency with the json file 
   1. see if could remove it from `managedIdentiy.json` and replace with inline refs instead
   2. do a hack in the generation

**Comment by markcowl** [comment] 2024-05-16 17:49
If this issue prevents correct / desired generation of greenfield APIs, then it should be high priority.  If this is about not breaking BrownField APIs that convert to TypeSpec, I am not sure it has the same priority.

**Comment by haolingdong-msft** [comment] 2024-05-20 03:34
> 1. Check with ARm Team what `UserAssignedIdentities` and `DelegatedResources` is meant for and if they might add known properties in the future
> 2. If not convert back to `alias`
> 3. To resolve inconsitency with the json file
>    
>    1. see if could remove it from `managedIdentiy.json` and replace with inline refs instead
>    2. do a hack in the generation

Hi @timotheeguerin , woule like to double confirm my understanding: Tsp team tends to change `typespec-azure-resource-manager` TSP and find other way to make .json consistent?

**Comment by haolingdong-msft** [comment] 2024-05-20 03:37
> If this issue prevents correct / desired generation of greenfield APIs, then it should be high priority. If this is about not breaking BrownField APIs that convert to TypeSpec, I am not sure it has the same priority.

It affects greenfield service generation, and almost half of the mgmt-plane services have `ManagedServiceIdentity`.

**Comment by allenjzhang** [comment] 2024-05-20 20:28
#868

**Comment by allenjzhang** [comment] 2024-05-22 18:57
Fixed with hotfix version 0.42.1 for `@azure-tools/typespec-azure-resource-manager`

**Closed by allenjzhang** 2024-05-22 18:57 UTC
Labels: TCGC, needs-triage, MPG Impact, needs-team-attention
