### ISSUE TITLE
Overwrite the expanded properties

### ISSUE THREAD

**Issue by pshao25** [Azure/typespec-azure#1362] opened 2024-08-13 05:34 UTC
Open up this issue to see if we could do something like:
```
model Original {
  a: string;
  @someDecorator("aaa")
  b: int;
}

model Updated is Original {
  @someDecorator("another value") <= change the original metadata
  b: anotherType; <= change the original type
}

// or
model Updated {
  ...Original;
  @someDecorator("another value") <= change the original metadata
  b: anotherType; <= change the original type
}
```
A specific example why I'm asking this is:

User defines a [ManagedResource](https://github.com/Azure/azure-rest-api-specs/blob/0077b4a8c5071d3ab33fd9f9ba013581c9a66b8f/specification/alertsmanagement/resource-manager/Microsoft.AlertsManagement/stable/2021-08-08/AlertProcessingRules.json#L445) , which has the same properties as those of [TrackedResource](https://github.com/Azure/azure-rest-api-specs/blob/0077b4a8c5071d3ab33fd9f9ba013581c9a66b8f/specification/common-types/resource-management/v3/types.json#L56), except that `ManagedResource` doesn't have such [visibilities](https://github.com/Azure/azure-rest-api-specs/blob/0077b4a8c5071d3ab33fd9f9ba013581c9a66b8f/specification/common-types/resource-management/v3/types.json#L66), it only has "read" and "create", not "update". If a model extends such `ManagedResource`, should we take this model as extending `TrackedResource`? i.e. should I write something like `model AlertProcessingRule is Azure.ResourceManager.TrackedResource<XXX>`? In .net generator, as long as the model has the same property (type, name, we don't even consider optionality) of `TrackedResource`, we regard it as `TrackedResource`. However, if we take `ManagedResource` as `TrackedResource`, we lose the overwritten information of visibility in this case.

Therefore, if we have the ability to overwrite the expanded properties, maybe we could do something like:
```
model ManagedResource {
  ...Azure.ResourceManager.Foundations.TrackedResource;
  @visibility("read", "create")
  tags: string;
}
// Or
model ManagedResource is Azure.ResourceManager.Foundations.TrackedResource {
  @visibility("read", "create")
  tags: string;
}
```

Please notice that this is just a specific example, we have many examples that is a rewrite of a `XXXResource` with modification of some properties.

**Comment by timotheeguerin** [comment] 2024-08-13 20:08
duplicate of https://github.com/microsoft/typespec/issues/1292

in the case where you just need to change the decorator you can augment
```
@@visbility(MangedResource.tags, "read", "create")
```

**Closed** 2024-08-13 20:09 UTC
Labels: needs-area

**Comment by pshao25** [comment] 2024-08-14 04:02
@timotheeguerin I saw that issue is two years ago. Is it still on track? Because as I stated in the last sentence, "this is just a specific example, we have many examples that is a rewrite of a XXXResource with modification of some properties." I'm not sure if all the cases could be resolved by argument decorators. Will put it here once come across these.

**Comment by timotheeguerin** [comment] 2024-08-14 04:14
like a lot of issues they are still tracked and on the backlog until we have real use case for it, if you have more please comment on that issue, vote and bring it up in the syncs if it is important)
