### ISSUE TITLE
[Feature Request] Adding @prop support to /** */

### ISSUE THREAD

**Issue by allenjzhang** [Azure/typespec-azure#28] opened 2023-12-15 01:53 UTC
Supporting @prop in JSDOC would all clearer read of the TypeSpec particularly.

```
/** Employee model
* @prop name The name of the employee.
* @prop age The age of the employee.
*/
mode Employee {
  name: string;

  age: int32;
}
```

Some considerations:

- Should we use a separator like ` - ` or using space.

```
* @prop name - Employee name

* @prop name Employee name
``` 

- Continue @param multi-line support approach (treat as multi-line until encounter next token)

**Comment by timotheeguerin** [comment] 2023-12-15 16:38
Dup of typespec core issue https://github.com/microsoft/typespec/issues/2211

**Comment by markcowl** [comment] 2023-12-18 19:21
closing as duplicate of https://github.com/microsoft/typespec/issues/2211

**Closed by markcowl** 2023-12-18 19:21 UTC
Labels: needs-triage
