### ISSUE TITLE
[Feature Request] Get ARM Server with hostParameters

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/typespec-azure#217] opened 2024-02-05 09:44 UTC
For ARM tsp, `getServers` from `typespec/http` will return a Server with no hostParameters. This is due to a synthesized Server generated by `@armProviderNamespace`:
https://github.com/Azure/typespec-azure/blob/8b8d7c05f168d9305a09691c4fedcb88f4a57652/packages/typespec-azure-resource-manager/src/namespace.ts#L121-L127

This is not enough for SDKs. Since we allow customers to set host, e.g. [Java](https://github.com/Azure/azure-sdk-for-java/blob/d5b1a8d1b009f57331df170056cc17cf7f6a2253/sdk/applicationinsights/azure-resourcemanager-applicationinsights/src/main/java/com/azure/resourcemanager/applicationinsights/ApplicationInsightsManager.java#L121):
```java
private ApplicationInsightsManager(HttpPipeline httpPipeline, AzureProfile profile, Duration defaultPollInterval) {
        Objects.requireNonNull(httpPipeline, "'httpPipeline' cannot be null.");
        Objects.requireNonNull(profile, "'profile' cannot be null.");
        this.clientObject =
            new ApplicationInsightsManagementClientBuilder()
                .pipeline(httpPipeline)
                .endpoint(profile.getEnvironment().getResourceManagerEndpoint()) // set host
                .subscriptionId(profile.getSubscriptionId())
                .defaultPollInterval(defaultPollInterval)
                .buildClient();
    }
```
we need a Server parameter with hostParameters. Previously this is done by modelerfour(I guess). 
#### Proposal:
We do either:
1. Provide a function `getArmServer` in TCGC to get the Server for ARM. When dealing with ARM, use `getArmServer` instead of current `getServers`, as ARM will probably have one server only.
2. Each language SDK handles on their own, e.g. [Java PR](https://github.com/Azure/autorest.java/pull/2532)
3. Change the `@armProviderNamespace` synthesized Server to have hostParameters. Though this will probably affect `typespec-autorest`, since it doesn't need hostParameters.
4. Implement it in `getAllOperations` in TCGC? (this I'm not sure)
 
I'm fine with both 1 and 2. There needs more discussion for 3 or 4.

**Comment by tadelesh** [comment] 2024-06-24 02:26
i vote for 3 since arm has different entry point. `@armProviderNamespace` should not hard code host value.

**Comment by haolingdong-msft** [comment] 2024-06-25 01:10
I also vote for 3, but it might impact the generated swagger, so we will need more input from TypeSpec ARM team.

**Comment by tadelesh** [comment] 2024-07-04 07:21
final decision: change arm decorator.

**Comment by haolingdong-msft** [comment] 2024-07-08 03:45
Hi @allenjzhang, may I know the plan for this issue? When will it be updated?

**Comment by timotheeguerin** [comment] 2024-07-10 23:21
It feels to me like changing the host for client should be something that is always available regardless of what is configured to test against localhost for example

**Comment by haolingdong-msft** [comment] 2024-07-10 23:48
@timotheeguerin  I agree we should be able to change the host for this ARM case, but not sure if it's always changable, as for unbranding, user can only allow a specific endpoint, but not able to change. The problem is for ARM case, current TypeSpec definition does not allow changing the host.

**Comment by allenjzhang** [comment] 2024-07-11 00:03
The host should always be settable by the client. For example, ARM also has different sovereign cloud and azure stack endpoints which client needs to specify. Making ARM spec have parameterized host seems overkill and not necessary.

**Comment by haolingdong-msft** [comment] 2024-07-11 00:07
I think we need to make ARM spec have parameterized host, otherwise it's not changeable. If we always treat the host as changable even with constant host url, the problem is non-azure may have needs to not change the host.

**Comment by timotheeguerin** [comment] 2024-07-11 01:45
So if someone wants to test with a test url(localhost or staging server) they have to make a different spec? This feels like a terrible experience, why not always allow it.

**Comment by haolingdong-msft** [comment] 2024-07-11 02:37
Hi @timotheeguerin, I don't have strong opinion on how to treat constant endpoint defined in TypeSpec. I'm fine with always treating the host as settable even it's a constant, as long as we have consistent behavior across Azure and non-Azure. 

We previously discussed with @srnagar and agreed we have scenarios that the host cannot be changed. Chenjie and I have a discussion with Allen just now, Allen will talk with SDK archs again and have agreement on how to treat constant host. @allenjzhang Please update if you have agreement, Thanks!

**Comment by iscai-msft** [comment] 2024-07-11 17:58
The decision following our sync was to first implement this in TCGC, with later consideration of moving this into the compiler. TCGC will special case host parameters to make them a string with a `clientDefaultValue`. Here is the issue to revisit it in the typespec compiler: https://github.com/microsoft/typespec/issues/3821

**Comment by timotheeguerin** [comment] 2024-07-11 18:05
Just to clarify here too but it should be the `baseUrl` that is overridable not the `host`(Basically the entire thing that `@server` would set

**Comment by allenjzhang** [comment] 2024-07-11 18:16
Per discussion in DPG sync meeting, we have discussed that:
1. Client with overridable host is fairly universal.
2. Having it centralized in TCGC to indicate the host is writeable is a good choice.

Issy opened issue to track the work item. https://github.com/microsoft/typespec/issues/3821

**Comment by timotheeguerin** [comment] 2024-07-11 18:36
Filed a dedicated issue for tcgc https://github.com/Azure/typespec-azure/issues/1153

**Closed by timotheeguerin** 2024-07-11 18:36 UTC
Labels: feature, lib:tcgc
