### ISSUE TITLE
typespec-azure-core - Azure.Core.Page<T> requires T to be a model

### ISSUE THREAD

**Issue by johanste** [Azure/typespec-azure#213] opened 2024-02-03 22:03 UTC
...this means I can't have a paged-of-scalars. We should remove this restriction. From what I can tell, the only reason for the restriction is to construct the friendly name/doc. 

Impacted service: schema registry.

**Comment by markcowl** [comment] 2024-02-07 17:44
duplicate of https://github.com/Azure/typespec-azure-pr/issues/3735

**Closed by markcowl** 2024-02-07 17:44 UTC
Labels: needs-triage
