### ISSUE TITLE
[Bug] getClientType doesn't give usage and namespace

### ISSUE THREAD

**Issue by pshao25** [Azure/typespec-azure#354] opened 2024-03-04 08:28 UTC
**Describe the bug**
For this case https://github.com/Azure/cadl-ranch/blob/228d218417abb3c73a70550b920685940195f281/packages/cadl-ranch-specs/http/type/union/main.tsp#L44 of this type `string | "b" | "c"`, when I call `getClientType`, the usage is None. The description is empty too.

**To Reproduce**

**Expected behavior**
Usage should be RoundTrip

**Additional context**

**Comment by lirenhe** [comment] 2024-03-04 08:43
cc @tadelesh and @iscai-msft

**Comment by tadelesh** [comment] 2024-03-05 03:46
Before you call `getClientType`, have you called `getAllModels`?

**Comment by tadelesh** [comment] 2024-03-12 03:31
@pshao25 I'll close this for now since I could not reproduce it. If you are still meet such problem, feel free to reopen and provide more info.

**Closed by tadelesh** 2024-03-12 03:31 UTC
Labels: bug, question, TCGC, needs-triage
